name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true  
 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo

    - name: Deploy FTP
      uses: sebastianpopp/ftp-action@master
      with:
        host: "youhide.com.br"
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "public"
        remoteDir: "/"
